version: 2
jobs:
  deploy:
    # This is a directory where all your repo content will be placed. 
    # Name is not that important at this case.
    working_directory: ~/app

    # Docker environment where we gonna run our build deployment scripts 
    docker:
    - image: circleci/node:8.11

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    
    # Install npm dependencies 🙂
    - run: npm install

    # Make things faster
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
    - deploy:
        filters:
          branches:
            only:
            - master